version: "3.1"

services:
  pf:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pd:636 -t 300 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-AnyHealth.git
      - SERVER_PROFILE_PATH=pingfed
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pd:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    env_file:
      - ~/.pingidentity/devops
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-AnyHealth.git
      - SERVER_PROFILE_PATH=pingdir
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet

  dg:
    image: pingidentity/pingdatagovernance:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pf:9031 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-AnyHealth.git
      - SERVER_PROFILE_PATH=datagov
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 443:443
    networks:
      - pingnet
                    
  console:
    image: pingidentity/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 8080:8080
    networks:
      - pingnet

networks:
    pingnet: